#NUMPY - a type of python library that provides a multidimensional array object
         At the core of the NumPy package, is the ndarray object.

In [ ]:
#creating numpy arry (array=table)

In [3]:
import numpy as np

In [5]:
np.array([2,4,56,422,32,1]) #it is an 1 dimensional array - (vector)

array([  2,   4,  56, 422,  32,   1])

In [9]:
a=np.array([2,4,56,422,32,1])
print(a)

[  2   4  56 422  32   1]


In [11]:
type(a)

numpy.ndarray

In [13]:
b=np.array([[45,34,22,2],[24,55,3,22]]) # 2d array - (Matrix)
b
            

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

In [19]:
c=np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]]) #3d array - (Tensor)
c

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [ ]:
 #dtype - The desired data-type for the array

In [23]:
np.array([11,23,44] , dtype=float)

array([11., 23., 44.])

In [29]:
np.array([11,23,44] , dtype=bool) #true cause,every non zero is true in python

array([ True,  True,  True])

In [31]:
np.array([0,0,23,] , dtype=bool) #if 0, false

array([False, False,  True])

In [33]:
np.array([11,23,44] , dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [35]:
np.array([11.44,23.11,44.23] , dtype=int)

array([11, 23, 44])

In [39]:
np.array([11.+0.j, 23.+0.j, 44.+0.j] , dtype=float)

TypeError: float() argument must be a string or a real number, not 'complex'

In [41]:
np.array([11., 23., 44.],dtype=int)

array([11, 23, 44])

In [ ]:
#Numpy array vs Python Sequences (NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. )

In [43]:
d= np.array([22,44,56,76.8,97.9]) #The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 
d

array([22. , 44. , 56. , 76.8, 97.9])

In [47]:
d= np.array([22,44,56,76.8,97.9,9+0j]) #The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 
d

array([22. +0.j, 44. +0.j, 56. +0.j, 76.8+0.j, 97.9+0.j,  9. +0.j])

In [ ]:
#ARANGE

In [49]:
np.arange(1,25) #arange function gives the numbers from 1 to 25 where 25(last element) is excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [59]:
np.arange(22,66)    #66 is excluded

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [61]:
np.arange(10,20,2) # by giving the 2 as 3rd argument skips the 2 elements

array([10, 12, 14, 16, 18])

In [63]:
np.arange(1,33,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [67]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#RESHAPE (#arange the given elements in to rows and coloums)

In [75]:
np.arange(1,10).reshape(3,3) #converts the numbers between 1 to 10 into 3 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.arange(1,11).reshape(5,2) #converted to 5 rows and 2 coloums

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:
np.arange(1,11).reshape(5,3) #Both of number products should be equal to number of Items present inside the array.
#error cause 5*3 is 12 and totals elements present in array is 10

ValueError: cannot reshape array of size 10 into shape (5,3)

In [81]:
np.arange(1,13).reshape(3,4) #converted to 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#ones and zeroes

In [83]:
np.ones((3,4)) #need to mention elements inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#random

In [93]:
np.random.random(3) #gives the random number 

array([0.76672764, 0.07680054, 0.39329682])

In [97]:
np.random.random((3,4)) #float datatype

array([[0.88699131, 0.61375381, 0.36783422, 0.32621258],
       [0.63205446, 0.97924361, 0.20112612, 0.54071606],
       [0.36125625, 0.73572987, 0.02825377, 0.63964543]])

In [114]:
np.random.randint((3,4)) #gives random int values

array([2, 3])

In [139]:
np.random.randint(1,40)

20

In [ ]:
#indexing and slicing

In [9]:
import numpy as np

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1=np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a1[0]

array([1, 2, 3])

In [33]:
a1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [35]:
a1[0,1]

2

In [51]:
a=np.arange(0,100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
a[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [59]:
a[1:5]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
a[::-1] #reverse the elements

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [65]:
a[-4,3]

63

In [71]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
a[1:4 , 2:3] #gives specific elements

array([[12],
       [22],
       [32]])

In [77]:
a[2:6 , 1: 7]

array([[21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46],
       [51, 52, 53, 54, 55, 56]])

In [79]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
a>50 #Boolean datatype

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [87]:
a!=50

False

In [95]:
a<100

True

In [97]:
a>20

True

In [105]:
G = np.random.randint(1,100,24).reshape(6,4) 
G

array([[15, 49,  9, 40],
       [64, 79, 60,  3],
       [70, 91, 79, 68],
       [42, 61, 17,  6],
       [79, 56, 20, 37],
       [10, 58, 87,  5]])

In [107]:
G>50 #find all numbers greater than 50

array([[False, False, False, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [109]:
G[G>50] #gives the numbers greater than 50

array([64, 79, 60, 70, 91, 79, 68, 61, 79, 56, 58, 87])

In [111]:
G % 2 == 0 #gives even numbers
  

array([[False, False, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [113]:
G[G % 2 == 0] #gives even numbers

array([40, 64, 60, 70, 68, 42,  6, 56, 20, 10, 58])

In [115]:
G[(G>50) & (G % 2 == 0)] #find all numbers greater than 50 and are even 

array([64, 60, 70, 68, 56, 58])

In [117]:
(G>50) & (G % 2 == 0)   #find all numbers greater than 50 and are even 

array([[False, False, False, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False]])